{% set version = "2.1.1" %}

package:
  name: cli-core-yo
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/40/6e/2d5b690639e684483b55633f88a68280b96a87cc00a87e860f784701e31c/cli_core_yo-{{ version }}.tar.gz
  sha256: cc73bc220e48051843294f4d4d97067492ce01b41b961a1da23ad6af39153c86

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61
    - setuptools-scm >=8
    - wheel
  run:
    - python >=3.10
    - click >=8.3,<9
    - rich >=14,<15
    - typer >=0.21,<0.22

test:
  imports:
    - cli_core_yo

about:
  home: https://pypi.org/project/cli-core-yo/
  summary: Reusable command-line interface kernel
  license: MIT
  license_file: LICENSE
